spring:
  application:
    name: ccshub

  datasource:
    url: jdbc:mysql://localhost:3306/dbccshub
    username: root
    password: Magno_rayvaughan123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/823cde44-4433-456d-b801-bdf0ab3d41fc/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: 67761468-57d5-41a3-9b4f-1f69101be135
            client-secret: JDb8Q~9YR51YTnNtJNDz6Y3nhX2CIHHnyjmqdbvf
            scope:
              - openid
              - email
              - profile

server:
  port: 8080
  address: 0.0.0.0
  error:
    include-stacktrace: never