spring:
  application:
    name: ccshub

  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: ${azure_issuer_uri}
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: ${azure_client_id}
            client-secret: ${azure_client_secret}
            scope:
              - openid
              - email
              - profile

server:
  port: 8080
  address: 0.0.0.0
  error:
    include-stacktrace: never